# Generated by Django 2.0.2 on 2018-02-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palier',
            name='palier_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
