# Generated by Django 2.0.2 on 2018-02-22 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='palier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_module', to='courses.Palier'),
        ),
    ]
