# Generated by Django 2.0.2 on 2018-02-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180222_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('trimestre', models.CharField(choices=[('t1', 'Trimestre 1'), ('t2', 'Trimestre 2'), ('t3', 'Trimestre 3')], max_length=20)),
                ('course_slug', models.SlugField(blank=True, unique=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_course', to='courses.Module')),
            ],
        ),
    ]
