# Generated by Django 2.0.2 on 2018-02-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        ('courses', '0006_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz'),
        ),
    ]
