# Generated by Django 2.0.2 on 2018-02-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_tutorial_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz'),
        ),
    ]
