# Generated by Django 2.0.2 on 2018-02-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180223_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Video'),
        ),
    ]
