# Generated by Django 2.0.2 on 2018-02-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180223_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
