# Generated by Django 2.0.2 on 2018-02-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_tutorial_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
