# Generated by Django 2.0.2 on 2018-02-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='order',
        ),
    ]
