# Generated by Django 2.0.2 on 2018-02-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_course_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
