# Generated by Django 2.0.2 on 2018-02-26 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0013_course_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='palier',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='palier',
            name='student',
            field=models.ManyToManyField(related_name='enrolled_palier', to=settings.AUTH_USER_MODEL),
        ),
    ]
