# Generated by Django 2.0.2 on 2018-02-26 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0014_auto_20180226_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='owned', to='courses.Palier')),
                ('user', models.OneToOneField(on_delete='related_course', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'My courses',
                'verbose_name': 'My courses',
            },
        ),
    ]
