# Generated by Django 2.0.2 on 2018-02-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birthdate',
            new_name='birth_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='palier',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_name',
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
