# Generated by Django 2.0.2 on 2018-02-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180225_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
